### ISSUE TITLE
Error, failed to find any more of line (iostream dead?) 

### ISSUE THREAD

**Issue by heikodietrich** [gap-packages/anupq#10]
As with the previous error, sporadically the following error shows up -- as before, I have failed to find could which can reproduce this error:

> > No space left on device
> > Error, failed to find any more of line (iostream dead?)
> > called from
> > ReadAllLine( iostream, true, IS_ALL_PQ_LINE ) called from
> > PQ_READ_NEXT_LINE( datarec.stream ) called from
> > FILTER_PQ_STREAM_UNTIL_PROMPT( datarec ); called from
> > ToPQ( datarec, [ 1 ], [ "  #default output" ] ); called from
> > PQ_PG_CONSTRUCT_DESCENDANTS( datarec ) called from
> > ###### 

I have 32GB RAM and more than 700GB free harddisc space, so I don't understand this error message; GAP is installed on that disc. I should mention that this happens when I do a lot of calls to PqDescendants... (constructing coclass trees)

**Comment by fingolfin** [comment]
"No space left on device" can appear even if there is still space left, as that message is also generated if the filesystem runs out of metadata resources (e.g. available inodes). See e.g. http://stackoverflow.com/questions/24671621/no-space-left-on-device

Assuming you are doing this on Linux (are you?), I should point out that a typical unix installation makes use of multiple file systems, mounted into a single file hierarchy. A wild guess: you system is using devfs for /dev, and GAP leaks pttys (see issue #11), causing more and more tty devices being allocated, which eventually overflow the devfs, resulting in this error.

You could check this, thouugh, by monitoring the conten of `/dev` during your computation, say using `du` and `df`, or possibly just by running `ls /dev | wc` before and during the computation.

Of course this is really just a wild guess, your troubles might be caused by a variation of the above, or even something completely different... :/
